CREATE TABLE IF NOT EXISTS profiles (
    subject VARCHAR(160) PRIMARY KEY,
    full_name VARCHAR(160) NOT NULL,
    email VARCHAR(180) NOT NULL,
    phone VARCHAR(40) NOT NULL,
    document_number VARCHAR(40) NOT NULL,
    address VARCHAR(240) NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS statement_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject VARCHAR(160) NOT NULL,
    posted_at TIMESTAMP NOT NULL,
    description VARCHAR(240) NOT NULL,
    amount DECIMAL(19, 2) NOT NULL,
    entry_type VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS pix_transfers (
    transaction_id VARCHAR(80) PRIMARY KEY,
    subject VARCHAR(160) NOT NULL,
    amount DECIMAL(19, 2) NOT NULL,
    recipient_key VARCHAR(160) NOT NULL,
    description VARCHAR(240),
    scenario VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    error_code VARCHAR(80),
    correlation_id VARCHAR(80) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

-- Feature 012: device post-quantum signing keys registered at enrollment.
CREATE TABLE IF NOT EXISTS device_signing_keys (
    subject VARCHAR(160) NOT NULL,
    device_id VARCHAR(160) NOT NULL,
    algorithm VARCHAR(20) NOT NULL,
    public_key VARBINARY(4096) NOT NULL,
    registered_at TIMESTAMP NOT NULL,
    PRIMARY KEY (subject, device_id)
);

-- Feature 012: one row per signed Pix order; the nonce primary key rejects replays.
CREATE TABLE IF NOT EXISTS pix_transaction_signatures (
    nonce VARCHAR(80) PRIMARY KEY,
    subject VARCHAR(160) NOT NULL,
    device_id VARCHAR(160) NOT NULL,
    transaction_id VARCHAR(80),
    algorithm VARCHAR(20) NOT NULL,
    signature VARBINARY(8192) NOT NULL,
    issued_at TIMESTAMP NOT NULL,
    verified_at TIMESTAMP NOT NULL
);
