CREATE TABLE IF NOT EXISTS profiles (
    subject VARCHAR(160) PRIMARY KEY,
    full_name VARCHAR(160) NOT NULL,
    email VARCHAR(180) NOT NULL,
    phone VARCHAR(40) NOT NULL,
    document_number VARCHAR(40) NOT NULL,
    address VARCHAR(240) NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS statement_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject VARCHAR(160) NOT NULL,
    posted_at TIMESTAMP NOT NULL,
    description VARCHAR(240) NOT NULL,
    amount DECIMAL(19, 2) NOT NULL,
    entry_type VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS pix_transfers (
    transaction_id VARCHAR(80) PRIMARY KEY,
    subject VARCHAR(160) NOT NULL,
    amount DECIMAL(19, 2) NOT NULL,
    recipient_key VARCHAR(160) NOT NULL,
    description VARCHAR(240),
    scenario VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    error_code VARCHAR(80),
    correlation_id VARCHAR(80) NOT NULL,
    created_at TIMESTAMP NOT NULL
);
